### ISSUE TITLE
Unexpected token.

### ISSUE THREAD

**Issue by KautilyaReddyRacha** [HeyPuter/puter#250]
> puter.com@1.0.0 start
> node run-selfhosted.js

file:///home/user/puter/run-selfhosted.js:98
    lines.push(error_help.title ?? error_help.text);
                                 ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
![Screenshot from 2024-04-08 16-01-48](https://github.com/HeyPuter/puter/assets/57624620/01333cfb-5aa3-4397-9f4a-45dcc93ff438)

**Comment by AtkinsSJ** [comment]
Hi, this error generally means that your version of Node.js is too old to understand some of the newer JS syntax we use. Can you run `node --version`? If it's less than 16 you'll need to update Node.

cc: @KernelDeimos, looks like the version-checker code requires too high a version. :laughing:

**Comment by KernelDeimos** [comment]
> cc: @KernelDeimos, looks like the version-checker code requires too high a version. 😆

You mean too low? I'm really surprised the version checker didn't catch this. We allow node.js 16+ and when I tested with node 16 it ran successfully.

@KautilyaReddyRacha can you type `node --version` and let us know what it says? That will help us debug the code that's supposed to show a more helpful error message.

**Comment by KernelDeimos** [comment]
@KautilyaReddyRacha If you pull again you should see this message:
![image](https://github.com/HeyPuter/puter/assets/7225168/30cdd5ee-12c6-4846-8dd0-8b3442999be3)

I think you're using node 13 or lower. This version has been EOL for 3 years so I recommend not using it for any purpose.
