### ISSUE TITLE
CompositeError: failed to initialize these services: database

### ISSUE THREAD

**Issue by liusanp** [HeyPuter/puter#258]
**Issue Description**

The first time I started, there was a table creation error.

**Steps to Reproduce**

**Expected & Actual Behavior**

**Addition Information or Screenshots (if applicable)**

```shell
{
    "error": "CompositeError: failed to initialize these services: database\n    at Container.init (/data/git/puter/packages/backend/src/services/Container.js:81:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Kernel._install_modules (/data/git/puter/packages/backend/src/Kernel.js:114:13)\n    at async /data/git/puter/packages/backend/src/Kernel.js:97:13\n    at async /data/git/puter/packages/backend/src/util/context.js:115:20\n    at async Context.arun (/data/git/puter/packages/backend/src/util/context.js:113:16)\n--- Inner error: SqliteError: table `user_to_user_permissions` already exists\n    at Database.exec (/data/git/puter/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)\n    at SqliteDatabaseAccessService._init (/data/git/puter/packages/backend/src/services/database/SqliteDatabaseAccessService.js:85:25)\n    at async SqliteDatabaseAccessService.init (/data/git/puter/packages/backend/src/services/BaseService.js:48:9)\n    at async Container.init (/data/git/puter/packages/backend/src/services/Container.js:73:17)\n    at async Kernel._install_modules (/data/git/puter/packages/backend/src/Kernel.js:114:13)\n    at async /data/git/puter/packages/backend/src/Kernel.js:97:13\n    at async /data/git/puter/packages/backend/src/util/context.js:115:20\n    at async Context.arun (/data/git/puter/packages/backend/src/util/context.js:113:16)\n--- End of inner error {\n  innerErrors: [\n    SqliteError: table `user_to_user_permissions` already exists\n        at Database.exec (/data/git/puter/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)\n        at SqliteDatabaseAccessService._init (/data/git/puter/packages/backend/src/services/database/SqliteDatabaseAccessService.js:85:25)\n        at async SqliteDatabaseAccessService.init (/data/git/puter/packages/backend/src/services/BaseService.js:48:9)\n        at async Container.init (/data/git/puter/packages/backend/src/services/Container.js:73:17)\n        at async Kernel._install_modules (/data/git/puter/packages/backend/src/Kernel.js:114:13)\n        at async /data/git/puter/packages/backend/src/Kernel.js:97:13\n        at async /data/git/puter/packages/backend/src/util/context.js:115:20\n        at async Context.arun (/data/git/puter/packages/backend/src/util/context.js:113:16) {\n      code: 'SQLITE_ERROR'\n    }\n  ],\n  originalStackDescriptor: {\n    get: [Function (anonymous)],\n    set: [Function (anonymous)],\n    enumerable: false,\n    configurable: true\n  }\n}"
}
```

**Tooling**
- [x] Development (`npm run start`)
- [x] Docker (via `docker run`)
- [x] Docker (via `docker-compose`)

**Puter version (if accessible)**
> Click the profile button on the top-right, then "Settings". The version number will be printed at the bottom

**Comment by KernelDeimos** [comment]
Hi, thanks for the report. I believe I finally understand what's going on - this will be fixed shortly

**Comment by KernelDeimos** [comment]
This issue should be fixed now: https://github.com/HeyPuter/puter/commit/eb66848aeecab888da86cbbe22dfbc0c90503fc0

Since this was a database initialization issue, you'll need to manually get your database version to be consistent. Here are a few ways to do that:
- clear the `data` (or `volatile/runtime`) directory (note: files on Puter will be lost if you do this!)
- use `sqlitebrowser` (or another tool) and manually execute the query `PRAGMA user_version=1;`
- manually remove the tables added by [this file](https://github.com/HeyPuter/puter/blob/main/packages/backend/src/services/database/sqlite_setup/0003_user-permissions.sql)
