### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by bambinounos** [HeyPuter/puter#359]
**Install error**

**Trying to install**

**Install succesfuly**

**internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node:path'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cli.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)**

**Deployment**
- [ ] Production (none)
- [ ] Development (`npm install`)

**Puter version (latest)**

**Comment by bambinounos** [comment]
I tried to re install npm, now it says /usr/bin/env: ‘node’: No such file or directory

**Comment by bambinounos** [comment]
hi @Eric-Lighthall nodejs version is v20.12.2

**Comment by bambinounos** [comment]
@Eric-Lighthall npm version is 10.5.0

**Comment by Eric-Lighthall** [comment]
> I tried to re install npm, now it says /usr/bin/env: ‘node’: No such file or directory

What shows up when you run the command ```which node```? The error ```/usr/bin/env: ‘node’: No such file or directory``` seems like it's an issue with the node installation.

Searching the error on google shows it's usually a naming problem with the path.

**Comment by bambinounos** [comment]
@Eric-Lighthall  which node command /home/ubuntu/.nvm/versions/node/v20.12.2/bin/node
