### ISSUE TITLE
Error when calling `puter.fs.readdir()` on a file path

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#417]
**Issue Description**
When calling `readdir()` on a path that is a file, not a directory, we get an internal error on the server, triggering an alarm.

**Steps to Reproduce**
In the Terminal:
- `touch foo.txt`
- `ls foo.txt`

Otherwise, if `/username/foo.txt` exists and is a file, run `puter.fs.readdir('/username/foo.txt')`.

**Expected & Actual Behavior**
The expected behaviour is that an error is returned to the user, but it should be something like `ENOTDIR`, not an internal server error.

**Addition Information or Screenshots (if applicable)**

Error details:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'win32' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/home/sam/Projects/HeyPuter/puter/node_modules/express/lib/response.js:1159:12)
    at ServerResponse.json (/home/sam/Projects/HeyPuter/puter/node_modules/express/lib/response.js:272:14)
    at ServerResponse.send (/home/sam/Projects/HeyPuter/puter/node_modules/express/lib/response.js:163:21)
    at /home/sam/Projects/HeyPuter/puter/packages/backend/src/routers/filesystem_api/readdir.js:116:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async errorHandledHandler (/home/sam/Projects/HeyPuter/puter/packages/backend/src/api/eggspress.js:183:14)
- error: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'win32' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/home/sam/Projects/HeyPuter/puter/node_modules/express/lib/response.js:1159:12)
    at ServerResponse.json (/home/sam/Projects/HeyPuter/puter/node_modules/express/lib/response.js:272:14)
    at ServerResponse.send (/home/sam/Projects/HeyPuter/puter/node_modules/express/lib/response.js:163:21)
    at /home/sam/Projects/HeyPuter/puter/packages/backend/src/routers/filesystem_api/readdir.js:116:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async errorHandledHandler (/home/sam/Projects/HeyPuter/puter/packages/backend/src/api/eggspress.js:183:14)
- url: '/readdir'
- method: 'POST'
- body: { path: '/Sam/run.sh' }
- headers: {
  host: 'api.puter.localhost:4100',
  connection: 'keep-alive',
  'content-length': '22',
  pragma: 'no-cache',
  'cache-control': 'no-cache',
  'sec-ch-ua': '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
  'content-type': 'application/json;charset=UTF-8',
  'sec-ch-ua-mobile': '?0',
  authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0IjoicyIsInYiOiIwLjAuMCIsInUiOiJUSUVLY0ZlaFFvS0IwOUxteTNOTTVBPT0iLCJ1dSI6IjJQTFVKNzFLU1MyUVROZlZ4ZUpUVVE9PSIsImlhdCI6MTcxNTMyOTM1OX0.Hxx5vGQL5OhoPJOK5zZAHoIz57WTgauCT5_6uD1bxlE',
  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
  'sec-ch-ua-platform': '"Linux"',
  accept: '*/*',
  origin: 'http://puter.localhost:4100',
  'sec-fetch-site': 'same-site',
  'sec-fetch-mode': 'cors',
  'sec-fetch-dest': 'empty',
  referer: 'http://puter.localhost:4100/',
  'accept-encoding': 'gzip, deflate, br, zstd',
  'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8'
}
```

**Deployment**
- [x] Production (puter.com)
- [x] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
Current main branch, which is at 1f6a2093fb0462ee3ddf682c3a55fc0697fb32b5

**Comment by KernelDeimos** [comment]
fixed by a72ec9799ac3bd76ceafa22cce149e373a13f3b9
